# Generated by Django 6.0.5 on 2026-06-29 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_horarias', to=settings.AUTH_USER_MODEL)),
                ('usuario_activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_horarias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SueldoHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sueldos_hora', to=settings.AUTH_USER_MODEL)),
                ('usuario_activo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sueldos_hora_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
