# Generated by Django 6.0.5 on 2026-06-29 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago_sueldo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargahoraria',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
