# Generated by Django 6.0.5 on 2026-07-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='rol_usuario',
        ),
    ]
